export default {
  CHANGE_THEME: 'CHANGE_THEME',
  INIT_THEME: 'INIT_THEME',

  POPULAR_FETCH: 'POPULAR_FETCH',
  POPULAR_FETCH_SUCCESS: 'POPULAR_FETCH_SUCCESS',
  POPULAR_FETCH_FAIL: 'POPULAR_FETCH_FAIL',
  POPULAR_FETCH_MORE_SUCCESS: 'POPULAR_FETCH_MORE_SUCCESS',
  POPULAR_FETCH_MORE_FAIL: 'POPULAR_FETCH_MORE_FAIL',

  TRENDING_FETCH: 'TRENDING_FETCH',
  TRENDING_FETCH_SUCCESS: 'TRENDING_FETCH_SUCCESS',
  TRENDING_FETCH_FAIL: 'TRENDING_FETCH_FAIL',
  TRENDING_FETCH_MORE_SUCCESS: 'TRENDING_FETCH_MORE_SUCCESS',
  TRENDING_FETCH_MORE_FAIL: 'TRENDING_FETCH_MORE_FAIL',

  FAVORITE_FETCH: 'FAVORITE_FETCH',
  FAVORITE_FETCH_SUCCESS: 'FAVORITE_FETCH_SUCCESS',
  FAVORITE_FETCH_FAIL: 'FAVORITE_FETCH_FAIL',
}
