export default {
  CHANGE_THEME: 'CHANGE_THEME',
  INIT_THEME: 'INIT_THEME',

  POPULAR_FETCH: 'POPULAR_FETCH',
  POPULAR_FETCH_SUCCESS: 'POPULAR_FETCH_SUCCESS',
  POPULAR_FETCH_FAIL: 'POPULAR_FETCH_FAIL',
  POPULAR_FETCH_MORE_SUCCESS: 'POPULAR_FETCH_MORE_SUCCESS',
  POPULAR_FETCH_MORE_FAIL: 'POPULAR_FETCH_MORE_FAIL',
}
